# Generated by Django 5.2.17 on 2026-09-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['asset', '-timestamp'], name='idx_quote_asset_time'),
        ),
    ]
